site_name: MkDocs Test Docs
site_description: Домашнее задание №4
theme: material
features:
    - navigation.indexes

nav:
  - Обзор: index.md
  - Начало работы:
    - Авторизация и аутентификация: getting_started/authorization.md
    - Примеры работы с API: getting_started/example.md
  - Справочник API: dist/index.html
  - Глоссарий: glossary.md
  - Релизы: releases.md
  - Контакты: contacts.md