site_name: MkDocs Test Docs
site_description: Домашнее задание №4
theme: material

nav:
  - Обзор: index.md
  - Начало работы:
    - section/getting_started.md
    - Авторизация и аутентификация: section/authorization.md
    - Примеры работы с API: section/example.md
  - Справочник API: dist/index.html
  - Глоссарий: glossary.md
  - Релизы: releases.md
  - Контакты: contacts.md